tuning:
  study_name: ttbar1L_stage1_reconstruction
  sqlite_path: /mnt/iusers01/fatpou01/phy01/w00238tl/scratch/HyPER_24_2/results/tuning_campaigns/stage1_v2/ttbar1L/stage1/study.sqlite3
  output_dir: /mnt/iusers01/fatpou01/phy01/w00238tl/scratch/HyPER_24_2/results/tuning_campaigns/stage1_v2/ttbar1L/stage1
dataset:
  root: /mnt/iusers01/fatpou01/phy01/w00238tl/scratch/HyPER_graph_dbs/schema2/ttbar1L
  source_h5_path: /mnt/iusers01/fatpou01/phy01/w00238tl/scratch/HyPER_24_2/HyPER_ttbarSL_typed/raw/training_dataset_even.h5
  train_set: training_dataset_even
  predict_set: training_dataset_even
  split:
    cache_path: /mnt/iusers01/fatpou01/phy01/w00238tl/scratch/HyPER_24_2/results/integration_validation/splits/ttbar1L_full_schema4.npz
    require_existing: true
    predict_split: null
  drop_last: false
predicting:
  split: null
  source_indices_file: null
trainer:
  run_test_after_fit: false
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
