dataset:          '/data/sdellasa/QT_HyPER_Training/tuples_Class/nobtag'
train_set:        'training_dataset_odd'
val_set:          'training_dataset_even'
train_val_split:  0.5
max_n_events:     -1
drop_last:        False

num_message_layers:   3
hyperedge_order:      3
message_feats:        64
hyperedge_feats:      128
dropout:              0.01

optimizer:            "Adam"
learning_rate:        0.001
criterion_edge:       "BCE"
criterion_hyperedge:  "BCE"
loss_reduction:       "mean"
alpha:                0.5
beta:                 0.005

epochs:       300
patience:     30
batch_size:   4096

device:       "cpu"
num_devices:   16

savedir: "HyPER_logs"
continue_from_ckpt: null

predict_set:    'ttbar_SL_even'
predict_with:   "cpu"
predict_model:  "/home/sdellasa/QT_HyPER_Training/HyPER_pygDataset/HyPER/HyPER_logs/version_118"
predict_output: "/data/sdellasa/QT_HyPER_Training/tuples_Class/predictions/ttbar_SL_v118_even.pkl"
topology: 'ttbar_single_lep'

onnx_output:   "HyPER.onnx"
convert_model: null