defaults:
  - ttH_SL_typed
  - _self_

config_name: ttH_SL_classification_only

classification:
  enabled: true

reconstruction:
  enabled: false

loss:
  edge_weight: 0.0
  hyperedge_weight: 0.0
  classification_weight: 1.0

predicting:
  output_mode: classifier
  overwrite: false

trainer:
  check_val_every_n_epoch: 1
  limit_val_batches: 1.0

early_stopping:
  enabled: true
  monitor: val_loss
  mode: min
  patience: 20
